### ISSUE TITLE
babylon vs acorn

### ISSUE THREAD

**Issue by aleclarson** [alangpierce/sucrase#227] opened 2018-06-01 16:20 UTC
What does [babylon][1] provide that [acorn][2] doesn't? I was under the impression that acorn is faster.

[1]: https://www.npmjs.com/package/babylon
[2]: https://www.npmjs.com/package/acorn

**Comment by MaxGraey** [comment] 2018-06-01 16:33
[Cherow](https://github.com/cherow/cherow) [much faster](https://cherow.github.io/cherow/performance/)

**Comment by alangpierce** [comment] 2018-06-02 04:44
Acorn doesn't support TypeScript and Flow (which I consider critical features of Sucrase), and has relatively little support for upcoming JS features. I think they have a policy of waiting for a JS proposal to be stage 4 before implementing. Babylon is nice because it supports basically everything, and even the TypeScript support is kept up-to-date by the TypeScript team. Another option was the TypeScript compiler, although that doesn't support Flow.

I'll take a closer look at Cherow when I get a chance; I had seen it, but assumed it wouldn't support TypeScript/Flow, but the README now says that it does. It looks like the author just started on TypeScript/Flow support in the last month, so I suspect it's not complete.

I expect the Sucrase parser is faster than all of these since it's solving a simpler problem (no validation, no AST). I'll try to get some real measurements, though.

**Comment by alangpierce** [comment] 2018-06-02 16:53
Interesting, I forked the Cherow performance tests and added a one-off build of the Sucrase parser, and looks like Cherow is still faster.

http://www.alangpierce.com/cherow/performance/

<img width="961" alt="screen shot 2018-06-02 at 9 49 38 am" src="https://user-images.githubusercontent.com/211605/40878756-55efecd8-664a-11e8-869e-4d7eec9d133e.png">

I'll see if there are optimizations or structural improvements from Cherow that I could pull in. At this point, the Sucrase parser has enough custom stuff that it certainly isn't easy to just drop in a different parser, but it'll be interesting to see what makes Cherow faster.

**Comment by aleclarson** [comment] 2018-06-02 17:32
@alangpierce And that includes AST generation, right?

**Comment by alangpierce** [comment] 2018-06-02 17:35
AST generation for everything but Sucrase, no AST generation for Sucrase (I removed the code for it).

**Comment by MaxGraey** [comment] 2018-06-02 18:05
So looks like in remove AST from cherow and intergate to Sucrase you can provide much better performance during parsing stage? But how about JSX? I'm not sure cherow support it

**Comment by kevinbarabash** [comment] 2018-06-02 23:56
It looks like Cherow doesn't support `flow` or `typescript`.  https://github.com/cherow/cherow/issues/96

**Comment by MaxGraey** [comment] 2018-06-03 00:00
Currently [typescript](https://github.com/cherow/cherow/tree/master/packages/cherow-ts) and [flow](https://github.com/cherow/cherow/tree/master/packages/cherow-flow) work in progress

**Comment by KFlash** [comment] 2018-06-03 00:21
Both TS and Flow are going to be implemented, and I'm almost done with the TS code. However I was "forced" to re-do some core stuff so ATM I'm finishing v. 2.0 of the parser before I complete it. E.g. the editor mode.
Seen from my point of view current Cherow have horrible performance, and it will all change in v. 2.0. I already improved it's performance with 15%

https://github.com/cherow/cherow/issues/98

**Comment by alangpierce** [comment] 2018-06-26 04:49
Closing this since I think there isn't anything specific to do here. Cherow has a different enough API from the Sucrase parser (an AST vs an array of annotated tokens and scopes) that it's not really reasonable to switch to Cherow without nearly rewriting Sucrase. I think there are a number of ways to further improve Sucrase performance, and I'll be exploring those when I get a chance.

That said, if anyone wants to hack together a Sucrase fork that uses Cherow, or wants to write a Sucrase competitor based on Cherow, I'd certainly be interested to see how it goes.

**Closed by alangpierce** 2018-06-26 04:49 UTC

**Comment by aleclarson** [comment] 2018-08-29 19:37
@alangpierce Heads up, [this link](http://www.alangpierce.com/cherow/performance) crashes with an error about `window.espree` not existing when I try to run the benchmarks.

**Comment by alangpierce** [comment] 2018-08-30 19:29
@aleclarson thanks, not sure what the problem is with that. My guess it's an issue with the CDN hosting espree, or espree was updated in a way that broke it. To be clear, the benchmark isn't being kept up-to-date, it was just a one-off test with the version of Sucrase at the time, so I'd need to redo the setup anyway if I wanted to do a perf test on more recent code.
