### ISSUE TITLE
Multi-line type definitions result in invalid output

### ISSUE THREAD

**Issue by kiliancs** [alangpierce/sucrase#391] opened 2019-01-03 21:20 UTC
Using Sucrase 3.9.2, the following examples result in invalid output:

```ts
interface Person {
  name: string;
  age: number;
}

// Invalid result in Sucrase
const multiLineArg = (
  a: {
    name: string;
    age: number;
  },
): Person => a;

// Invalid result in Sucrase
const multiLineReturn = (
  a: Person,
): {
  name: string;
  age: number;
} => a;

// Invalid result in Sucrase
const multiLineConst: {
    name: srtring;
    age: number;
} = {};
```

Compare with tsc:

https://sucrase.io/#compareWithBabel=false&compareWithTypeScript=true&compressedCode=H4sIAE98LlwAA52PQQrCMBBF9znFXyoI3TdUEFeCC9ETxDiWQDOFSeKm5O6mFREqIrp8s3hvvuNIcjWWcCAJPWNQABtPNUIUx60ubNqCnPyZRKusVFVhxzfTuQuEQuoiHOOUrJhAyvYcIny5ur1j2kiLBovRUk%2Fyd%2F0sAOSVWtbPh5o1jP6teaSYhF%2FZh2mSfp%2F3T3A74myefNpXChiyvgM8nXcEegEAAA%3D%3D

**Comment by alangpierce** [comment] 2019-01-03 22:21
Thanks! Looks to me like only `multiLineReturn` is actually invalid? It's intentional that Sucrase keeps spacing from the original code; that way the line numbers always match up exactly. In most cases, things still parse just fine, but I guess arrow functions are trickier. The most straightforward thing I can think of is to move the `)` to just before the `=>`, but that still seems like a bit of a pain.

**Comment by kiliancs** [comment] 2019-01-03 23:23
> Looks to me like only multiLineReturn is actually invalid?

Uhmm you are right that the other ones evaluate just fine in the browser. Something in Webpack is complaining, though. Hmmm.

I think moving the `)` to the same line as `=>` would indeed be the best solution, like you suggest.

**Comment by alangpierce** [comment] 2019-01-03 23:43
Drat. Webpack uses the acorn parser, so it's possible there could be a bug fix to that. Generally I do think that sucrase + webpack should be a combination that this project officially supports, so there might need to be some trick here to make it work in webpack.

**Comment by kiliancs** [comment] 2019-01-06 06:52
So I did some investigation and webpack 4.28.2 uses acorn ^5.6.2, webpack 5.0.0-alpha.3 uses acorn "^6.0.0".

And run the examples through a few acorn versions:

### acorn 6.0.5 
* multiLineArg: ✓ 
* multiLineReturn: SyntaxError: Unexpected token (3:0) 
* multiLineConst: ✓ 

### acorn 6.0.1 
* multiLineArg: ✓ 
* multiLineReturn: SyntaxError: Unexpected token (3:0) 
* multiLineConst: ✓ 

### acorn 5.7.3 (latest 5.x release)
* multiLineArg: SyntaxError: Unexpected token (6:0) 
* multiLineReturn: SyntaxError: Unexpected token (3:0) 
* multiLineConst: ✓ 

### acorn 5.6.2
* multiLineArg: SyntaxError: Unexpected token (6:0) 
* multiLineReturn: SyntaxError: Unexpected token (3:0) 
* multiLineConst: ✓ 

So for multiline returrn it looks like the solution is for sucrase change the location of the argument parenthesis, and for the other two the solution seems to use acorn 6. So either a webpack 4 release using acorn 6 or wait for webpack 5 to be released, for anyone having this problem (aka me).

**Comment by alangpierce** [comment] 2019-01-06 07:20
Cool, thanks for investigating! Annoying that `multiLineArg` doesn't work with webpack right now. I guess in my codebase it hasn't come up because we tend to use `function` syntax for top-level declarations.

FYI if you use yarn, you can set a `resolutions` value in package.json to force webpack 4 to use acorn 6: https://yarnpkg.com/lang/en/docs/selective-version-resolutions/ . (It might break, of course, depending on what breaking changes were in acorn 6, but it might fix things.)

Given that it'll fix itself with webpack 5 (or maybe a webpack 4 update), I'd prefer to avoid adding a workaround in Sucrase. But happy to reconsider if it's really causing trouble and there aren't other workarounds.

So that leaves `multiLineReturn` as the only one in scope of this issue, and it's definitely a Sucrase bug (I just confirmed that it doesn't parse in Chrome, Firefox, or Safari).

**Comment by kiliancs** [comment] 2019-01-06 08:05
Thanks for pointing out about yarn's `resolutions`, which I didn't think about. In this specific project we use npm and I suspect switching might be a hard sell, but maybe an easier sell if it comes with the tsc vs sucrase speedups for our dev work :) If forcing acorn 6 just works, that is. I'll give it a try.

FYI I opened a webpack issue https://github.com/webpack/webpack/issues/8593 to see if it would be ok to upgrade to acorn 6 in a webpack 4 release. I agree it doesn't make sense for Sucrase to try to workaround these, and that only `multiLineReturn` is actually a Sucrase bug.

**Comment by alangpierce** [comment] 2019-01-06 17:11
@kiliancs looks like https://github.com/rogeriochaves/npm-force-resolutions might be a way to override resolutions without needing to switch to yarn.

**Comment by alangpierce** [comment] 2019-01-06 17:18
I just landed a `multiLineReturn` fix, and will try to get a release out soon.

**Closed** 2019-01-06 17:18 UTC

**Comment by kiliancs** [comment] 2019-01-07 06:58
@alangpierce thanks for the pointer to force resolutions, and also thanks for fixing this so quickly! Great job!
